attrib -h *.vs
attrib -h .vs\AWsecretary\v17\.suo
del/Q .vs\AWsecretary\v17\INI\*.*
del/Q .vs\AWsecretary\v17\*.*
del/Q .vs\AWsecretary\v17\.suo
del/Q .vs\AWsecretary\config
del/Q .vs\AWsecretary\DesignTimeBuild
rd .vs\AWsecretary\config
rd .vs\AWsecretary\DesignTimeBuild
rd .vs\AWsecretary\v17
rd .vs\AWsecretary
rd .vs

attrib -h .vs\AWsecretary\v17\.suo
del/Q .vs\AWsecretary\v17\INI\*.*
del/Q .vs\AWsecretary\v17\.suo
del/Q .vs\AWsecretary\FileContentIndex\*.*
rd .vs\AWsecretary\FileContentIndex
rd .vs\AWsecretary\v17
rd .vs\AWsecretary
rd .vs

del/Q AWsecretary\obj\Debug\net8.0\Razor\Views\Messageboard\*.*
del/Q AWsecretary\obj\Debug\net8.0\Razor\Views\Shared\*.*
del/Q AWsecretary\obj\Debug\net8.0\Razor\Views\Home\*.*
del/Q AWsecretary\obj\Debug\net8.0\Razor\Views\*.*
del/Q AWsecretary\obj\Debug\net8.0\staticwebassets\*.*
del/Q AWsecretary\obj\Debug\net8.0\ref\*.*
del/Q AWsecretary\obj\Debug\net8.0\refint\*.*
del/Q AWsecretary\obj\Debug\net8.0\*.*
del/Q AWsecretary\obj\*.*
del/Q AWsecretary\bin\Debug\net8.0\Settings\*.*
del/Q AWsecretary\bin\Debug\net8.0\x86\*.*
del/Q AWsecretary\bin\Debug\net8.0\x64\*.*
del/Q AWsecretary\bin\Debug\net8.0\INI\*.*
del/Q AWsecretary\bin\Debug\net8.0\Log\*.*
del/Q AWsecretary\bin\Debug\net8.0\cs\*.*
del/Q AWsecretary\bin\Debug\net8.0\de\*.*
del/Q AWsecretary\bin\Debug\net8.0\es\*.*
del/Q AWsecretary\bin\Debug\net8.0\fr\*.*
del/Q AWsecretary\bin\Debug\net8.0\it\*.*
del/Q AWsecretary\bin\Debug\net8.0\ja\*.*
del/Q AWsecretary\bin\Debug\net8.0\ko\*.*
del/Q AWsecretary\bin\Debug\net8.0\pl\*.*
del/Q AWsecretary\bin\Debug\net8.0\pt-BR\*.*
del/Q AWsecretary\bin\Debug\net8.0\refs\*.*
del/Q AWsecretary\bin\Debug\net8.0\ru\*.*
del/Q AWsecretary\bin\Debug\net8.0\runtimes\*.*
del/Q AWsecretary\bin\Debug\net8.0\runtimes\unix\lib\netcoreapp2.1\*.*
del/Q AWsecretary\bin\Debug\net8.0\runtimes\win\lib\netcoreapp2.1\*.*
del/Q AWsecretary\bin\Debug\net8.0\runtimes\win\lib\netcoreapp2.0\*.*
del/Q AWsecretary\bin\Debug\net8.0\runtimes\win\lib\netstandard2.0\*.*
del/Q AWsecretary\bin\Debug\net8.0\runtimes\win-x64\native\*.*
del/Q AWsecretary\bin\Debug\net8.0\tr\*.*
del/Q AWsecretary\bin\Debug\net8.0\zh-Hans\*.*
del/Q AWsecretary\bin\Debug\net8.0\zh-Hant\*.*
del/Q AWsecretary\bin\Debug\net8.0\*.*
del/Q AWsecretary\bin\Debug\Settings\*.*
del/Q AWsecretary\bin\Debug\x86\*.*
del/Q AWsecretary\bin\Debug\x64\*.*
del/Q AWsecretary\bin\Debug\INI\*.*
del/Q AWsecretary\bin\Debug\Log\*.*
del/Q AWsecretary\bin\Debug\*.*
del/Q AWsecretary\bin\Debug\*.trc
del/Q AWsecretary\bin\Debug\net8.0\*.trc

del/Q AWsecretary\obj\Release\net8.0\Razor\Views\Messageboard\*.*
del/Q AWsecretary\obj\Release\net8.0\Razor\Views\Shared\*.*
del/Q AWsecretary\obj\Release\net8.0\Razor\Views\Home\*.*
del/Q AWsecretary\obj\Release\net8.0\Razor\Views\*.*
del/Q AWsecretary\obj\Release\net8.0\staticwebassets\*.*
del/Q AWsecretary\obj\Release\net8.0\ref\*.*
del/Q AWsecretary\obj\Release\net8.0\refint\*.*
del/Q AWsecretary\obj\Release\net8.0\*.*
del/Q AWsecretary\obj\*.*
del/Q AWsecretary\bin\Release\net8.0\*.*
del/Q AWsecretary\bin\Release\net8.0\Settings\*.*
del/Q AWsecretary\bin\Release\net8.0\x86\*.*
del/Q AWsecretary\bin\Release\net8.0\x64\*.*
del/Q AWsecretary\bin\Release\net8.0\INI\*.*
del/Q AWsecretary\bin\Release\net8.0\Log\*.*
del/Q AWsecretary\bin\Release\net8.0\cs\*.*
del/Q AWsecretary\bin\Release\net8.0\de\*.*
del/Q AWsecretary\bin\Release\net8.0\es\*.*
del/Q AWsecretary\bin\Release\net8.0\fr\*.*
del/Q AWsecretary\bin\Release\net8.0\it\*.*
del/Q AWsecretary\bin\Release\net8.0\ja\*.*
del/Q AWsecretary\bin\Release\net8.0\ko\*.*
del/Q AWsecretary\bin\Release\net8.0\pl\*.*
del/Q AWsecretary\bin\Release\net8.0\pt-BR\*.*
del/Q AWsecretary\bin\Release\net8.0\refs\*.*
del/Q AWsecretary\bin\Release\net8.0\ru\*.*
del/Q AWsecretary\bin\Release\net8.0\runtimes\*.*
del/Q AWsecretary\bin\Release\net8.0\runtimes\unix\lib\netcoreapp2.1\*.*
del/Q AWsecretary\bin\Release\net8.0\runtimes\win\lib\netcoreapp2.1\*.*
del/Q AWsecretary\bin\Release\net8.0\runtimes\win\lib\netcoreapp2.0\*.*
del/Q AWsecretary\bin\Release\net8.0\runtimes\win\lib\netstandard2.0\*.*
del/Q AWsecretary\bin\Release\net8.0\runtimes\win-x64\native\*.*
del/Q AWsecretary\bin\Release\net8.0\tr\*.*
del/Q AWsecretary\bin\Release\net8.0\zh-Hans\*.*
del/Q AWsecretary\bin\Release\net8.0\zh-Hant\*.*
del/Q AWsecretary\bin\Release\net8.0\*.*
del/Q AWsecretary\bin\Release\Settings\*.*
del/Q AWsecretary\bin\Release\x86\*.*
del/Q AWsecretary\bin\Release\x64\*.*
del/Q AWsecretary\bin\Release\INI\*.*
del/Q AWsecretary\bin\Release\Log\*.*
del/Q AWsecretary\bin\Release\*.*
del/Q AWsecretary\bin\Release\*.trc
del/Q AWsecretary\bin\Release\net8.0\*.trc

rd AWsecretary\obj\Debug\net8.0\Razor\Views\Messageboard
rd AWsecretary\obj\Debug\net8.0\Razor\Views\Shared
rd AWsecretary\obj\Debug\net8.0\Razor\Views\Home
rd AWsecretary\obj\Debug\net8.0\Razor\Views
rd AWsecretary\obj\Debug\net8.0\Razor
rd AWsecretary\obj\Debug\net8.0\staticwebassets
rd AWsecretary\obj\Debug\net8.0\ref
rd AWsecretary\obj\Debug\net8.0\refint
rd AWsecretary\obj\Debug\net8.0
rd AWsecretary\obj\Debug
rd AWsecretary\obj
rd AWsecretary\bin\Debug\net8.0
rd AWsecretary\bin\Debug\net8.0\Settings
rd AWsecretary\bin\Debug\net8.0\INI
rd AWsecretary\bin\Debug\net8.0\Log
rd AWsecretary\bin\Debug\net8.0\x86
rd AWsecretary\bin\Debug\net8.0\x64
rd AWsecretary\bin\Debug\net8.0\cs
rd AWsecretary\bin\Debug\net8.0\de
rd AWsecretary\bin\Debug\net8.0\es
rd AWsecretary\bin\Debug\net8.0\fr
rd AWsecretary\bin\Debug\net8.0\it
rd AWsecretary\bin\Debug\net8.0\ja
rd AWsecretary\bin\Debug\net8.0\ko
rd AWsecretary\bin\Debug\net8.0\pl
rd AWsecretary\bin\Debug\net8.0\pt-BR
rd AWsecretary\bin\Debug\net8.0\refs
rd AWsecretary\bin\Debug\net8.0\ru
rd AWsecretary\bin\Debug\net8.0\runtimes\unix\lib\netcoreapp2.1
rd AWsecretary\bin\Debug\net8.0\runtimes\unix\lib
rd AWsecretary\bin\Debug\net8.0\runtimes\unix
rd AWsecretary\bin\Debug\net8.0\runtimes\win\lib\netcoreapp2.1
rd AWsecretary\bin\Debug\net8.0\runtimes\win\lib\netcoreapp2.0
rd AWsecretary\bin\Debug\net8.0\runtimes\win\lib\netstandard2.0
rd AWsecretary\bin\Debug\net8.0\runtimes\win\lib
rd AWsecretary\bin\Debug\net8.0\runtimes\win
rd AWsecretary\bin\Debug\net8.0\runtimes\win-x64\native
rd AWsecretary\bin\Debug\net8.0\runtimes\win-x64
rd AWsecretary\bin\Debug\net8.0\runtimes
rd AWsecretary\bin\Debug\net8.0\tr
rd AWsecretary\bin\Debug\net8.0\zh-Hans
rd AWsecretary\bin\Debug\net8.0\zh-Hant
rd AWsecretary\bin\Debug\net8.0
rd AWsecretary\bin\Debug\Settings
rd AWsecretary\bin\Debug\INI
rd AWsecretary\bin\Debug\Log
rd AWsecretary\bin\Debug\x86
rd AWsecretary\bin\Debug\x64
rd AWsecretary\bin\Debug

rd AWsecretary\obj\Release\net8.0\Razor\Views\Messageboard
rd AWsecretary\obj\Release\net8.0\Razor\Views\Shared
rd AWsecretary\obj\Release\net8.0\Razor\Views\Home
rd AWsecretary\obj\Release\net8.0\Razor\Views
rd AWsecretary\obj\Release\net8.0\Razor
rd AWsecretary\obj\Release\net8.0\staticwebassets
rd AWsecretary\obj\Release\net8.0
rd AWsecretary\obj\Release
rd AWsecretary\obj
rd AWsecretary\bin\Release\net8.0\Settings
rd AWsecretary\bin\Release\net8.0\INI
rd AWsecretary\bin\Release\net8.0\Log
rd AWsecretary\bin\Release\net8.0\x86
rd AWsecretary\bin\Release\net8.0\x64
rd AWsecretary\bin\Release\net8.0\cs
rd AWsecretary\bin\Release\net8.0\de
rd AWsecretary\bin\Release\net8.0\es
rd AWsecretary\bin\Release\net8.0\fr
rd AWsecretary\bin\Release\net8.0\it
rd AWsecretary\bin\Release\net8.0\ja
rd AWsecretary\bin\Release\net8.0\ko
rd AWsecretary\bin\Release\net8.0\pl
rd AWsecretary\bin\Release\net8.0\pt-BR
rd AWsecretary\bin\Release\net8.0\refs
rd AWsecretary\bin\Release\net8.0\ru
rd AWsecretary\bin\Release\net8.0\runtimes\unix\lib\netcoreapp2.1
rd AWsecretary\bin\Release\net8.0\runtimes\unix\lib
rd AWsecretary\bin\Release\net8.0\runtimes\unix
rd AWsecretary\bin\Release\net8.0\runtimes\win\lib\netcoreapp2.1
rd AWsecretary\bin\Release\net8.0\runtimes\win\lib\netcoreapp2.0
rd AWsecretary\bin\Release\net8.0\runtimes\win\lib\netstandard2.0
rd AWsecretary\bin\Release\net8.0\runtimes\win\lib
rd AWsecretary\bin\Release\net8.0\runtimes\win
rd AWsecretary\bin\Release\net8.0\runtimes\win-x64\native
rd AWsecretary\bin\Release\net8.0\runtimes\win-x64
rd AWsecretary\bin\Release\net8.0\runtimes
rd AWsecretary\bin\Release\net8.0\tr
rd AWsecretary\bin\Release\net8.0\zh-Hans
rd AWsecretary\bin\Release\net8.0\zh-Hant
rd AWsecretary\bin\Release\net8.0
rd AWsecretary\bin\Release\Settings
rd AWsecretary\bin\Release\INI
rd AWsecretary\bin\Release\Log
rd AWsecretary\bin\Release\x86
rd AWsecretary\bin\Release\x64


del/Q AWsecretary\bin\Release\publish\Settings\*.*
del/Q AWsecretary\bin\Release\publish\x86\*.*
del/Q AWsecretary\bin\Release\publish\x64\*.*
del/Q AWsecretary\bin\Release\publish\INI\*.*
del/Q AWsecretary\bin\Release\publish\Log\*.*
del/Q AWsecretary\bin\Release\publish\cs\*.*
del/Q AWsecretary\bin\Release\publish\de\*.*
del/Q AWsecretary\bin\Release\publish\es\*.*
del/Q AWsecretary\bin\Release\publish\fr\*.*
del/Q AWsecretary\bin\Release\publish\it\*.*
del/Q AWsecretary\bin\Release\publish\ja\*.*
del/Q AWsecretary\bin\Release\publish\ko\*.*
del/Q AWsecretary\bin\Release\publish\pl\*.*
del/Q AWsecretary\bin\Release\publish\pt-BR\*.*
del/Q AWsecretary\bin\Release\publish\refs\*.*
del/Q AWsecretary\bin\Release\publish\ru\*.*
del/Q AWsecretary\bin\Release\publish\runtimes\*.*
del/Q AWsecretary\bin\Release\publish\runtimes\unix\lib\netcoreapp2.1\*.*
del/Q AWsecretary\bin\Release\publish\runtimes\win\lib\netcoreapp2.1\*.*
del/Q AWsecretary\bin\Release\publish\runtimes\win\lib\netcoreapp2.0\*.*
del/Q AWsecretary\bin\Release\publish\runtimes\win\lib\netstandard2.0\*.*
del/Q AWsecretary\bin\Release\publish\runtimes\win-x64\native\*.*
del/Q AWsecretary\bin\Release\publish\tr\*.*
del/Q AWsecretary\bin\Release\publish\zh-Hans\*.*
del/Q AWsecretary\bin\Release\publish\zh-Hant\*.*
del/Q AWsecretary\bin\Release\publish\*.*
del/Q AWsecretary\bin\Release\publish\Settings\*.*
del/Q AWsecretary\bin\Release\publish\x86\*.*
del/Q AWsecretary\bin\Release\publish\x64\*.*
del/Q AWsecretary\bin\Release\publish\INI\*.*
del/Q AWsecretary\bin\Release\publish\Log\*.*
del/Q AWsecretary\bin\Release\publish\*.*
del/Q AWsecretary\bin\Release\publish\*.trc
del/Q AWsecretary\bin\Release\publish\wwwroot\css\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\js\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\bootstrap\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\bootstrap\dist\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\bootstrap\dist\css\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\bootstrap\dist\js\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\jquery\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\jquery\dist\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\jquery\css\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\jquery\js\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation\dist\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation\css\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation\js\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive\dist\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive\css\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive\js\*.*
del/Q AWsecretary\bin\Release\publish\wwwroot\*.*

rd AWsecretary\bin\Release\publish\Settings
rd AWsecretary\bin\Release\publish\INI
rd AWsecretary\bin\Release\publish\Log
rd AWsecretary\bin\Release\publish\x86
rd AWsecretary\bin\Release\publish\x64
rd AWsecretary\bin\Release\publish\cs
rd AWsecretary\bin\Release\publish\de
rd AWsecretary\bin\Release\publish\es
rd AWsecretary\bin\Release\publish\fr
rd AWsecretary\bin\Release\publish\it
rd AWsecretary\bin\Release\publish\ja
rd AWsecretary\bin\Release\publish\ko
rd AWsecretary\bin\Release\publish\pl
rd AWsecretary\bin\Release\publish\pt-BR
rd AWsecretary\bin\Release\publish\refs
rd AWsecretary\bin\Release\publish\ru
rd AWsecretary\bin\Release\publish\runtimes\unix\lib\netcoreapp2.1
rd AWsecretary\bin\Release\publish\runtimes\unix\lib
rd AWsecretary\bin\Release\publish\runtimes\unix
rd AWsecretary\bin\Release\publish\runtimes\win\lib\netcoreapp2.1
rd AWsecretary\bin\Release\publish\runtimes\win\lib\netcoreapp2.0
rd AWsecretary\bin\Release\publish\runtimes\win\lib\netstandard2.0
rd AWsecretary\bin\Release\publish\runtimes\win\lib
rd AWsecretary\bin\Release\publish\runtimes\win
rd AWsecretary\bin\Release\publish\runtimes\win-x64\native
rd AWsecretary\bin\Release\publish\runtimes\win-x64
rd AWsecretary\bin\Release\publish\runtimes
rd AWsecretary\bin\Release\publish\tr
rd AWsecretary\bin\Release\publish\zh-Hans
rd AWsecretary\bin\Release\publish\zh-Hant
rd AWsecretary\bin\Release\publish
rd AWsecretary\bin\Release\publish\Settings
rd AWsecretary\bin\Release\publish\INI
rd AWsecretary\bin\Release\publish\Log
rd AWsecretary\bin\Release\publish\x86
rd AWsecretary\bin\Release\publish\x64
rd AWsecretary\bin\Release\publish\wwwroot\css
rd AWsecretary\bin\Release\publish\wwwroot\js
rd AWsecretary\bin\Release\publish\wwwroot\lib\bootstrap\dist\css
rd AWsecretary\bin\Release\publish\wwwroot\lib\bootstrap\dist\js
rd AWsecretary\bin\Release\publish\wwwroot\lib\bootstrap\dist
rd AWsecretary\bin\Release\publish\wwwroot\lib\jquery\css
rd AWsecretary\bin\Release\publish\wwwroot\lib\jquery\js
rd AWsecretary\bin\Release\publish\wwwroot\lib\jquery\dist
rd AWsecretary\bin\Release\publish\wwwroot\lib\jquery
rd AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation\css
rd AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation\js
rd AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation\dist
rd AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation
rd AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive\css
rd AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive\js
rd AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive\dist
rd AWsecretary\bin\Release\publish\wwwroot\lib\jquery-validation-unobtrusive
rd AWsecretary\bin\Release\publish\wwwroot\lib\bootstrap
rd AWsecretary\bin\Release\publish\wwwroot\lib
rd AWsecretary\bin\Release\publish\wwwroot
rd AWsecretary\bin\Release\publish

rd AWsecretary\bin\Release

rd AWsecretary\bin

del/Q AWsecretary\obj\Debug\TempPE\*.*
del/Q AWsecretary\obj\Debug\*.*
del/Q AWsecretary\obj\Release\TempPE\*.*
del/Q AWsecretary\obj\Release\*.*

rd AWsecretary\obj\Debug\TempPE
rd AWsecretary\obj\Debug
rd AWsecretary\obj\Release\TempPE
rd AWsecretary\obj\Release
rd AWsecretary\obj